name: Release notes
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install @semantic-release/commit-analyzer @semantic-release/release-notes-generator

      - name: Generate release notes
        id: release-notes-preview
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0

      - name: Comment on the Pull Request
        if: steps.release-notes-preview.outputs.releaseNotes
        uses: thollander/actions-comment-pull-request@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment_includes: "release notes"
          message: |
            Below is a preview of the release notes if your PR gets merged.

            ---

            ${{ steps.release-notes-preview.outputs.releaseNotes }}
